meta_product_name: "QL Gordon"
meta_title: "QL Gordon - graphisme & web"
meta_description: "Besoin d'un designer qui sait coder ?"
meta_image: "/app/assets/images/png/qlgordon.png" # should exist in `app/assets/images/`
twitter_account: "@qlgordon"   # required for Twitter Cards
